#!/bin/bash
# SessionStart hook: keep Scripts/data_pipeline/.env in sync with cloud-injected
# environment variables (mirrored from GitHub repository secrets).
#
# Behavior: for each known key, if the environment variable is set and
# non-empty in the session, write that value into .env. If the env var is
# missing, preserve whatever value is already in .env (so manually-populated
# values survive across resume/clear/compact events that re-fire this hook).
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

ENV_DIR="$CLAUDE_PROJECT_DIR/Scripts/data_pipeline"
ENV_FILE="$ENV_DIR/.env"

mkdir -p "$ENV_DIR"

KEYS=(
  FRED_API_KEY
  BLS_API_KEY
  BEA_API_KEY
  KIMI_API_KEY
  TG_API_KEY
  LIGHTHOUSE_DB_PATH
  SANTIMENT_API_KEY
  DUNE_API_KEY
  COINGLASS_API_KEY
)

declare -A existing=()
if [ -f "$ENV_FILE" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac
    name="${line%%=*}"
    value="${line#*=}"
    [ -n "$name" ] && existing["$name"]="$value"
  done < "$ENV_FILE"
fi

resolve() {
  local name="$1"
  local env_value="${!name:-}"
  if [ -n "$env_value" ]; then
    printf '%s' "$env_value"
  else
    printf '%s' "${existing[$name]:-}"
  fi
}

tmp="$(mktemp)"
{
  echo "# Auto-generated by .claude/hooks/session-start.sh"
  echo "# Mirrors GitHub repository secrets into the cloud session."
  echo "# A key whose env var is unset will keep its previous value."
  for name in "${KEYS[@]}"; do
    printf '%s=%s\n' "$name" "$(resolve "$name")"
  done
} > "$tmp"

mv "$tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Also export values into the session so code paths that don't use python-dotenv
# (e.g. when the package isn't installed) still see the keys.
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  for name in "${KEYS[@]}"; do
    value="$(resolve "$name")"
    [ -z "$value" ] && continue
    escaped="${value//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf 'export %s="%s"\n' "$name" "$escaped" >> "$CLAUDE_ENV_FILE"
  done
fi

missing=()
for required in FRED_API_KEY BLS_API_KEY BEA_API_KEY; do
  if [ -z "$(resolve "$required")" ]; then
    missing+=("$required")
  fi
done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "session-start: warning: required keys still empty in .env: ${missing[*]}" >&2
  echo "session-start: configure them as GitHub repository secrets so they are mirrored into the cloud session." >&2
fi

echo "session-start: wrote $ENV_FILE"
